apps/web/urls.py
# En el archivo urls.py en tu proyecto principal
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from .views import login_view,ResultadoAnalisisDetailView,Usuarios,eliminar_venta,eliminar_fase,editar_fase,FasesListView,crear_cotizacion,editar_cliente,crear_cliente,editar_proveedor,crear_proveedor,crear_usuario,editar_insumo,crear_compra,crear_insumo,crear_servicio,crear_inventario,crear_sucursal,EditarSucursal,RegistrarVenta,EditarUsuario,eliminar_cotizacion,eliminar_cliente,eliminar_recibo,eliminar_proveedor,eliminar_insumo,eliminar_compra,eliminar_sucursal,Inicio,eliminar_servicio,eliminar_inventario,eliminar_usuario,ResultadoAnalisis,Clientes,Cotizaciones,Ventas,Facturas,Recibos,Sucursales,Servicios,Inventarios,Compras,Insumos,Proveedores
from django.contrib.auth.views import LogoutView

app_name = 'web' 

urlpatterns = [

    path('', login_view, name='login'),
    path('logout/', login_required(LogoutView.as_view(next_page="web:login")), name='logout'),
    path('dashboard', login_required(Inicio.as_view()),name='inicio'), 
    path('analisis', login_required(ResultadoAnalisis.as_view()),name='analisis'), 
    path('facturas', login_required(Facturas.as_view()),name='facturas'), 
    path('recibos', login_required(Recibos.as_view()),name='recibos'), 
    re_path(r'^recibos/eliminar/(?P<id_recibo>[-\w]+)/$', login_required(eliminar_recibo), name='eliminar_recibo'),
    path('sucursales', login_required(Sucursales.as_view()),name='sucursales'),
    re_path(r'^sucursales/eliminar/(?P<id_sucursal>[-\w]+)/$', login_required(eliminar_sucursal), name='eliminar_sucursal'),
    path('sucursales/editar/<str:pk>/', EditarSucursal.as_view(), name='editar_sucursal'),
    path('sucursales/crear/', crear_sucursal, name='crear_sucursal'),
    path('servicios', Servicios.as_view(),name='servicios'),
    re_path(r'^servicios/eliminar/(?P<id_servicio>[-\w]+)/$', login_required(eliminar_servicio), name='eliminar_servicio'),
    path('servicios/crear/', crear_servicio, name='crear_servicio'),
    path('inventarios', Inventarios.as_view(),name='inventarios'),
    re_path(r'^inventarios/eliminar/(?P<id_inventario>[-\w]+)/$', login_required(eliminar_inventario), name='eliminar_inventario'),
    path('inventarios/crear/', crear_inventario, name='crear_inventario'),
    path('compras', Compras.as_view(),name='compras'),
    re_path(r'^compras/eliminar/(?P<id_compra>[-\w]+)/$', login_required(eliminar_compra), name='eliminar_compra'),
    path('compras/crear/', crear_compra, name='crear_compra'),
    path('insumos', Insumos.as_view(),name='insumos'),
    re_path(r'^insumos/eliminar/(?P<id_insumo>[-\w]+)/$', login_required(eliminar_insumo), name='eliminar_insumo'),
    path('insumos/crear/', crear_insumo, name='crear_insumo'),
    path('insumos/editar/<str:id_insumo>/', editar_insumo, name='editar_insumo'),
    path('proveedores', Proveedores.as_view(),name='proveedores'),
    path('proveedores/editar/<str:id_proveedor>/', editar_proveedor, name='editar_proveedor'),
    re_path(r'^proveedores/eliminar/(?P<id_proveedor>[-\w]+)/$', login_required(eliminar_proveedor), name='eliminar_proveedor'),
    path('proveedores/crear/', crear_proveedor, name='crear_proveedor'),
    path('clientes', Clientes.as_view(),name='clientes'),
    re_path(r'^clientes/eliminar/(?P<id_cliente>[-\w]+)/$', login_required(eliminar_cliente), name='eliminar_cliente'),
    path('clientes/crear/', crear_cliente, name='crear_cliente'),
    path('clientes/editar/<str:id_cliente>/', editar_cliente, name='editar_cliente'),
    path('cotizaciones', Cotizaciones.as_view(),name='cotizaciones'),
    re_path(r'^cotizaciones/eliminar/(?P<id_cotizacion>[-\w]+)/$', login_required(eliminar_cotizacion), name='eliminar_cotizacion'),
    path('cotizaciones/crear/', crear_cotizacion, name='crear_cotizacion'),
    path('ventas', Ventas.as_view(),name='ventas'),
    re_path(r'^ventas/eliminar/(?P<id_venta>[-\w]+)/$', login_required(eliminar_venta), name='eliminar_venta'),
    path('ventas/registrar/', login_required(RegistrarVenta.as_view()), name='registrar_venta'),
    path('usuarios', login_required(Usuarios.as_view()),name='usuarios'),
    re_path(r'^usuarios/eliminar/(?P<id>\d+)/$', login_required(eliminar_usuario), name='eliminar_usuario'),
    path('usuarios/editar/<int:pk>/', EditarUsuario.as_view(), name='editar_usuario'),
    path('usuarios/crear', crear_usuario, name='crear_usuario'),

    path('fases', FasesListView.as_view(), name='fases'),  # Puedes ajustar la URL según tu preferencia
    path('fases/editar/<str:id_fase>/', editar_fase, name='editar_fase'),
    re_path(r'^fases/eliminar/(?P<id_fase>[-\w]+)/$', login_required(eliminar_fase), name='eliminar_fase'),

    path('resultado_analisis/<str:id_resultado>/', ResultadoAnalisisDetailView.as_view(), name='detalle_resultado'),

]

config/urls.py
# En el archivo urls.py en tu proyecto principal
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



admin.site.site_header  =  "IMPRENTA"  
admin.site.site_title  =  "Administracion"
admin.site.index_title  =  "Servicios de Imprenta"

urlpatterns = [
    path('',include('apps.web.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/ventas/models.py
from django.db import models
import uuid
import shortuuid
from apps.compras.models import Insumo
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.db.models.signals import post_save
import google.generativeai as palm
from dotenv import load_dotenv
from translate import Translator
import os
from apps.empresa.models import Servicio
import requests
from easygoogletranslate import EasyGoogleTranslate
from datetime import datetime, timedelta
import pywhatkit 
from django.db.models.signals import pre_save


def conver_encode():
    u = uuid.uuid4()
    s = shortuuid.encode(u)
    return s


class Cliente(models.Model):
    id_cliente = models.CharField(
        primary_key=True,
        max_length=100,
        unique=True,
        default=conver_encode,
        editable=False,
    )
    nombre = models.CharField(
        max_length=155, blank=False, null=False, verbose_name="Nombres"
    )
    apellidos = models.CharField(
        max_length=255, blank=False, null=False, verbose_name="Apellidos"
    )
    direccion = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Direccion"
    )
    correo_electronico = models.EmailField(
        max_length=255, blank=False, null=False, verbose_name="Correo Electrónico"
    )
    celular = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Número de celular"
    )
    nit = models.CharField(max_length=55, blank=True, null=True, verbose_name="NIT")
    razon_social = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Razón social"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre + " " + self.apellidos

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"
        db_table = "cliente"

CHOICES_FASE = [
    ("Pendiente", "Pendiente"),
    ("Rayado y corte", "Rayado y corte"),
    ("Impresion", "Impresion"),
    ("Acabado final", "Acabado final"),
    ("Entregado", "Entregado"),
]

class Fase(models.Model):
    id_fase = models.CharField(
        primary_key=True,
        max_length=100,
        unique=True,
        default=conver_encode,
        editable=False,
    )
    cliente = models.ForeignKey(
        Cliente,
        blank=True,
        null=True,
        related_name="fases",
        on_delete=models.CASCADE,
        verbose_name="Cliente",
    )
    fase = models.CharField(
        max_length=125,
        verbose_name="Fase",
        choices=CHOICES_FASE,
        blank=True,
        null=True,
    )
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Fase"
        verbose_name_plural = "Fases"
        db_table = "fase"



class Cotizacion(models.Model):
    id_cotizacion = models.CharField(
        primary_key=True,
        max_length=100,
        unique=True,
        default=conver_encode,
        editable=False,
    )
    cliente = models.ForeignKey(
        Cliente,
        blank=True,
        null=True,
        related_name="cotizaciones",
        on_delete=models.CASCADE,
        verbose_name="Cliente",
    )
    insumos = models.ManyToManyField(Insumo, verbose_name="Insumos")
    total = models.FloatField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Total de la cotizacion",
        editable=False,
    )
    impuesto = models.IntegerField(
        default=0, blank=False, null=False, verbose_name="Impuesto (%)"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id_cotizacion

    class Meta:
        verbose_name = "Cotizacion"
        verbose_name_plural = "Cotizaciones"
        db_table = "cotizacion"


@receiver(m2m_changed, sender=Cotizacion.insumos.through)
def update_total_on_insumos_change(sender, instance, **kwargs):
    precios_insumos = [insumo.precio for insumo in instance.insumos.all()]
    suma_precios = sum(precios_insumos)

    if instance.impuesto > 0:
        impuesto_calculado = (suma_precios * instance.impuesto) / 100
        instance.total = suma_precios + impuesto_calculado
    else:
        instance.total = suma_precios

    instance.save()


CHOICES_TIPO = [
    ("Servicio", "Servicio"),
    ("Compra", "Compra"),
]


class Factura(models.Model):
    id_factura = models.CharField(
        primary_key=True,
        max_length=100,
        unique=True,
        default=conver_encode,
        editable=False,
    )
    nit = models.CharField(max_length=55, blank=True, null=True, verbose_name="NIT")
    razon_social = models.CharField(
        max_length=255, blank=True, null=True, verbose_name="Razón social"
    )
    tipo = models.CharField(
        max_length=125,
        verbose_name="Tipo",
        choices=CHOICES_TIPO,
        blank=False,
        null=False,
    )
    detalle = models.TextField(
        max_length=800, blank=True, null=True, verbose_name="Detalle"
    )
    total = models.FloatField(blank=False, null=False, verbose_name="Total")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id_compra

    class Meta:
        verbose_name = "Factura"
        verbose_name_plural = "Facturas"
        db_table = "factura"


CHOICES_TIPO = [
    ("Servicio", "Servicio"),
    ("Compra", "Compra"),
]


class Recibo(models.Model):
    id_recibo = models.CharField(
        primary_key=True,
        max_length=100,
        unique=True,
        default=conver_encode,
        editable=False,
    )
    tipo = models.CharField(
        max_length=125,
        verbose_name="Tipo",
        choices=CHOICES_TIPO,
        blank=False,
        null=False,
    )
    detalle = models.TextField(
        max_length=800, blank=True, null=True, verbose_name="Detalle"
    )
    total = models.FloatField(blank=False, null=False, verbose_name="Total")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id_recibo

    class Meta:
        verbose_name = "Recibo"
        verbose_name_plural = "Recibos"
        db_table = "recibo"


CHOICES_TIPO = [
    ("Servicio", "Servicio"),
]


class Venta(models.Model):
    id_venta = models.CharField(
        primary_key=True,
        max_length=100,
        unique=True,
        default=conver_encode,
        editable=False,
    )
    cliente = models.ForeignKey(
        Cliente,
        blank=False,
        null=False,
        related_name="ventas",
        on_delete=models.CASCADE,
        verbose_name="Cliente",
    )
    tipo = models.CharField(
        max_length=125,
        verbose_name="Tipo",
        choices=CHOICES_TIPO,
        blank=False,
        null=False,
    )
    inventario = models.ForeignKey(
        "empresa.Inventario",
        blank=False,
        null=False,
        related_name="ventas",
        on_delete=models.CASCADE,
        verbose_name="Inventario",
    )
    costo_impresion = models.FloatField(
        default=0, blank=False, null=False, verbose_name="Costo de Impresion"
    )
    costo_trabajo = models.FloatField(
        default=0, blank=False, null=False, verbose_name="Costo de Trabajo"
    )
    total_venta = models.FloatField(
        default=0,
        blank=False,
        null=False,
        verbose_name="Total de la venta",
        editable=False,
    )
    factura = models.BooleanField(default=False, verbose_name="Facturado")
    insumos = models.ManyToManyField(
        Insumo, verbose_name="Insumos", related_name="detalles_ventas"
    )
    impuesto_iva = models.IntegerField(
        default=13,
        blank=False,
        null=False,
        verbose_name="IMPUESTO IVA %",
        editable=False,
    )
    impuesto_it = models.IntegerField(
        default=3, blank=False, null=False, verbose_name="IMPUESTO IT %", editable=False
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id_venta
    



    class Meta:
        verbose_name = "Venta"
        verbose_name_plural = "Ventas"
        db_table = "venta"


@receiver(m2m_changed, sender=Venta.insumos.through)
def handle_insumos_changed(sender, instance, action, **kwargs):
    if action == "post_add" or action == "post_remove":
        update_stock_and_totals(instance)

tiempo_actual = datetime.now()
tiempo_margen = tiempo_actual + timedelta(minutes=1)

def update_stock_and_totals(venta):
    from apps.empresa.models import StockInsumo

    # Calcula el total de la venta
    suma_precios = sum(insumo.precio for insumo in venta.insumos.all())
    venta.total_venta = suma_precios + venta.costo_impresion + venta.costo_trabajo

    # Aplica impuestos si la venta está facturada
    if venta.factura:
        impuesto_total = venta.impuesto_iva + venta.impuesto_it
        venta.total_venta += (venta.total_venta * impuesto_total) / 100

        # Verifica si ya existe una factura para esta venta
        factura_existente = Factura.objects.filter(
            tipo="Servicio", detalle__icontains=f"Detalle del servicio {venta.id_venta}"
        ).first()

        if factura_existente:
            # Actualiza el total de la factura existente
            factura_existente.total = venta.total_venta
            factura_existente.save()
        else:
            # Crea la factura
            factura = Recibo(
                nit=venta.cliente.nit,
                razon_social=venta.cliente.razon_social,
                tipo="Servicio",

templates/pages/sucursales/crear.html
{% extends 'index.html' %}

{% block contenido %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body text-center">
                <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                    <h4 class="card-title">CREAR SUCURSAL</h4>
                    <a href="{% url 'web:sucursales' %}" class="btn " style="border-radius: 10px;background-color: rgb(224, 224, 224);font-weight: bold;padding: 10px;color: rgb(92, 92, 92);align-items: center;">Cancelar</a>
                </div>

                <div class="table-responsive" style="width: 100%;display: flex;justify-content: center;padding: 20px;">
                    <form method="post" style="max-width: 250px;display: flex;flex-direction: column;align-items: center;text-align: left;gap: 5px;">
                        {% csrf_token %}
                        <div style="width: 100%;">
                            {{ form.as_p }}
                        </div>
            

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {% for error in form.non_field_errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div id="loadingMessage" style="display: none;">
                            <p>Guardando cambios, por favor espere...</p>
                            <!-- Puedes añadir aquí un ícono de carga si lo deseas -->
                        </div>

                        <button class="btn btn-primary" style="margin-top: 10px;" type="submit" id="submitBtn">Guardar Sucursal</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        // Selección del formulario en lugar del botón
        document.querySelector('form').addEventListener('submit', function() {
            // Muestra el mensaje de carga
            document.getElementById('loadingMessage').style.display = 'block';
            // Deshabilita el botón de envío para evitar envíos múltiples
            document.getElementById('submitBtn').disabled = true;
        });
    </script>
</div>
{% endblock %}

templates/pages/sucursales/edit.html
{% extends 'index.html' %}

{% block contenido %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body text-center">
                <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                    <h4 class="card-title">EDITAR SUCURSAL</h4>
                    <a href="{% url 'web:sucursales' %}" class="btn " style="border-radius: 10px;background-color: rgb(224, 224, 224);font-weight: bold;padding: 10px;color: rgb(92, 92, 92);align-items: center;" >Cancelar</a>
                </div>

                <div class="table-responsive" style="width: 100%;display: flex;justify-content: center;padding: 20px;">
                    <form method="post" style="max-width: 250px;display: flex;flex-direction: column;align-items: center;text-align: left;gap: 5px;">
                        {% csrf_token %}
                        <label for="id_nombre" style="text-align: left;width: 100%;margin: 0px;">Nombre:</label>
                        <input type="text" class="form-control" id="id_nombre" name="nombre" value="{{ sucursal.nombre }}">

                        <label for="id_direccion" style="text-align: left;width: 100% ;margin: 0px;">Dirección:</label>
                        <input type="text" class="form-control" id="id_direccion" name="direccion" value="{{ sucursal.direccion }}">

                        <label for="id_latitud" style="text-align: left;width: 100% ;margin: 0px;">Latitud:</label>
                        <input type="text" class="form-control" id="id_latitud" name="latitud" value="{{ sucursal.latitud }}">

                        <label for="id_longitud" style="text-align: left;width: 100% ;margin: 0px;">Longitud:</label>
                        <input type="text" class="form-control" id="id_longitud" name="longitud" value="{{ sucursal.longitud }}">

                        {% if form.non_field_errors %}
                            <div class="alert alert-danger">
                                {% for error in form.non_field_errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div id="loadingMessage" style="display: none;">
                            <p>Guardando cambios, por favor espere...</p>
                            <!-- Puedes añadir aquí un ícono de carga si lo deseas -->
                        </div>

                        <button class="btn btn-primary" style="margin-top: 10px;" type="submit" id="submitBtn">Guardar Sucursal</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        // Selección del formulario en lugar del botón
        document.querySelector('form').addEventListener('submit', function() {
            // Muestra el mensaje de carga
            document.getElementById('loadingMessage').style.display = 'block';
            // Deshabilita el botón de envío para evitar envíos múltiples
            document.getElementById('submitBtn').disabled = true;
        });
    </script>
</div>
{% endblock %}

templates/pages/sucursales/sucursales.html
{% extends 'index.html' %}

{% block contenido %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body text-center">
            <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                <h4 class="card-title">SUCURSALES</h4>
                <a href="{% url 'web:crear_sucursal' %}" class="btn btn-primary style="border-radius: 10px;font-weight: bold;padding: 10px;color: white;align-items: center;" ><svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 5px;" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>Registrar Sucursal</a>
              </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                    <th style="text-align: left;">Nombre</th>
                    <th style="text-align: left;">Direccion</th>
                    <th style="text-align: left;">Latitud</th>
                    <th style="text-align: left;">Longitud</th>
                    <th>Acciones</th>
                  
                </tr>
              </thead>
              <tbody>
                {% for sucursal in sucursales %}
                <tr>
                    <td style="text-align: left;">{{sucursal.nombre}}</td>
                    <td style="text-align: left;">{{sucursal.direccion}}</td>
                    <td style="text-align: left;"> {{sucursal.latitud}}</td>
                    <td style="text-align: left;"> {{sucursal.longitud}}</td>
                    <td>
                      <div style="display: flex; justify-content: center; gap: 5px; align-items: center;">
                        <a href="{% url 'web:editar_sucursal' pk=sucursal.id_sucursal %}" type="button" class="btn btn-secondary text-white" style="padding:10px;" ">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M3 21v-4.25L16.2 3.575q.3-.275.663-.425t.762-.15q.4 0 .775.15t.65.45L20.425 5q.3.275.438.65T21 6.4q0 .4-.137.763t-.438.662L7.25 21zM17.6 7.8L19 6.4L17.6 5l-1.4 1.4z"/></svg> </a> 
                        <button type="button" class="btn btn-danger" style="padding:10px;" data-toggle="modal" data-target="#confirmDeleteModal{{ sucursal.id_sucursal }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19 4h-3.5l-1-1h-5l-1 1H5v2h14M6 19a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7H6v12Z"/></svg>
                        </button>
                    </div>
                    <div class="modal fade" id="confirmDeleteModal{{ sucursal.id_sucursal }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalLabel">Confirmar Eliminación</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    ¿Estás seguro de que deseas eliminar esta sucursal? <br>
                                    <strong> {{sucursal.nombre}}</strong>
                                   
                                </div>
                                <div class="modal-footer">
                                    <!-- Formulario para enviar la solicitud de eliminación -->
                                    <form action="{% url 'web:eliminar_sucursal' id_sucursal=sucursal.id_sucursal %}" method="post">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <input type="submit" class="btn btn-danger" value="Eliminar">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    </td>
                </tr>
                
                    
                {% endfor %}
               
              </tbody>
            </table>
            {% if not sucursales %}
            <div style="width: 100%;text-align: center;justify-content: center;padding: 10px;">
                <div style="text-align: center;width: 100%;justify-content: center;">No hay sucursales registrados</div>
            </div>
            {% endif %}
            <div class="pagination" style="width: 100%;justify-content: center;align-items: center;">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; primera</a>
                        <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
                    {% endif %}
            
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <strong>{{ num }}</strong>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <a href="?page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
            
                    <span class="current">
                        Página {{ page_obj.number }} de {{ items.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">siguiente</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
                    {% endif %}
                </span>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    
    
    
  </div>
{% endblock %}