apps/web/urls.py
# En el archivo urls.py en tu proyecto principal
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from .views import login_view,ResultadoAnalisisDetailView,Usuarios,eliminar_venta,eliminar_fase,editar_fase,FasesListView,crear_cotizacion,editar_cliente,crear_cliente,editar_proveedor,crear_proveedor,crear_usuario,editar_insumo,crear_compra,crear_insumo,crear_servicio,crear_inventario,crear_sucursal,EditarSucursal,RegistrarVenta,EditarUsuario,eliminar_cotizacion,eliminar_cliente,eliminar_recibo,eliminar_proveedor,eliminar_insumo,eliminar_compra,eliminar_sucursal,Inicio,eliminar_servicio,eliminar_inventario,eliminar_usuario,ResultadoAnalisis,Clientes,Cotizaciones,Ventas,Facturas,Recibos,Sucursales,Servicios,Inventarios,Compras,Insumos,Proveedores
from django.contrib.auth.views import LogoutView

app_name = 'web' 

urlpatterns = [

    path('', login_view, name='login'),
    path('logout/', login_required(LogoutView.as_view(next_page="web:login")), name='logout'),
    path('dashboard', login_required(Inicio.as_view()),name='inicio'), 
    path('analisis', login_required(ResultadoAnalisis.as_view()),name='analisis'), 
    path('facturas', login_required(Facturas.as_view()),name='facturas'), 
    path('recibos', login_required(Recibos.as_view()),name='recibos'), 
    re_path(r'^recibos/eliminar/(?P<id_recibo>[-\w]+)/$', login_required(eliminar_recibo), name='eliminar_recibo'),
    path('sucursales', login_required(Sucursales.as_view()),name='sucursales'),
    re_path(r'^sucursales/eliminar/(?P<id_sucursal>[-\w]+)/$', login_required(eliminar_sucursal), name='eliminar_sucursal'),
    path('sucursales/editar/<str:pk>/', EditarSucursal.as_view(), name='editar_sucursal'),
    path('sucursales/crear/', crear_sucursal, name='crear_sucursal'),
    path('servicios', Servicios.as_view(),name='servicios'),
    re_path(r'^servicios/eliminar/(?P<id_servicio>[-\w]+)/$', login_required(eliminar_servicio), name='eliminar_servicio'),
    path('servicios/crear/', crear_servicio, name='crear_servicio'),
    path('inventarios', Inventarios.as_view(),name='inventarios'),
    re_path(r'^inventarios/eliminar/(?P<id_inventario>[-\w]+)/$', login_required(eliminar_inventario), name='eliminar_inventario'),
    path('inventarios/crear/', crear_inventario, name='crear_inventario'),
    path('compras', Compras.as_view(),name='compras'),
    re_path(r'^compras/eliminar/(?P<id_compra>[-\w]+)/$', login_required(eliminar_compra), name='eliminar_compra'),
    path('compras/crear/', crear_compra, name='crear_compra'),
    path('insumos', Insumos.as_view(),name='insumos'),
    re_path(r'^insumos/eliminar/(?P<id_insumo>[-\w]+)/$', login_required(eliminar_insumo), name='eliminar_insumo'),
    path('insumos/crear/', crear_insumo, name='crear_insumo'),
    path('insumos/editar/<str:id_insumo>/', editar_insumo, name='editar_insumo'),
    path('proveedores', Proveedores.as_view(),name='proveedores'),
    path('proveedores/editar/<str:id_proveedor>/', editar_proveedor, name='editar_proveedor'),
    re_path(r'^proveedores/eliminar/(?P<id_proveedor>[-\w]+)/$', login_required(eliminar_proveedor), name='eliminar_proveedor'),
    path('proveedores/crear/', crear_proveedor, name='crear_proveedor'),
    path('clientes', Clientes.as_view(),name='clientes'),
    re_path(r'^clientes/eliminar/(?P<id_cliente>[-\w]+)/$', login_required(eliminar_cliente), name='eliminar_cliente'),
    path('clientes/crear/', crear_cliente, name='crear_cliente'),
    path('clientes/editar/<str:id_cliente>/', editar_cliente, name='editar_cliente'),
    path('cotizaciones', Cotizaciones.as_view(),name='cotizaciones'),
    re_path(r'^cotizaciones/eliminar/(?P<id_cotizacion>[-\w]+)/$', login_required(eliminar_cotizacion), name='eliminar_cotizacion'),
    path('cotizaciones/crear/', crear_cotizacion, name='crear_cotizacion'),
    path('ventas', Ventas.as_view(),name='ventas'),
    re_path(r'^ventas/eliminar/(?P<id_venta>[-\w]+)/$', login_required(eliminar_venta), name='eliminar_venta'),
    path('ventas/registrar/', login_required(RegistrarVenta.as_view()), name='registrar_venta'),
    path('usuarios', login_required(Usuarios.as_view()),name='usuarios'),
    re_path(r'^usuarios/eliminar/(?P<id>\d+)/$', login_required(eliminar_usuario), name='eliminar_usuario'),
    path('usuarios/editar/<int:pk>/', EditarUsuario.as_view(), name='editar_usuario'),
    path('usuarios/crear', crear_usuario, name='crear_usuario'),

    path('fases', FasesListView.as_view(), name='fases'),  # Puedes ajustar la URL según tu preferencia
    path('fases/editar/<str:id_fase>/', editar_fase, name='editar_fase'),
    re_path(r'^fases/eliminar/(?P<id_fase>[-\w]+)/$', login_required(eliminar_fase), name='eliminar_fase'),

    path('resultado_analisis/<str:id_resultado>/', ResultadoAnalisisDetailView.as_view(), name='detalle_resultado'),

]

config/urls.py
# En el archivo urls.py en tu proyecto principal
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



admin.site.site_header  =  "IMPRENTA"  
admin.site.site_title  =  "Administracion"
admin.site.index_title  =  "Servicios de Imprenta"

urlpatterns = [
    path('',include('apps.web.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/pages/cotizaciones/cotizaciones.html
{% extends 'index.html' %}

{% block contenido %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body text-center">
            <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                <h4 class="card-title">COTIZACIONES</h4>
                <a href="{% url 'web:crear_cotizacion' %}" class="btn btn-primary style="border-radius: 10px;font-weight: bold;padding: 10px;color: white;align-items: center;" ><svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 5px;" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>Registrar Cotizacion</a>
              </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                    <th style="text-align: left;">Cliente</th>
                    <th style="text-align: left;">Detalle del acabado</th>
                    <th style="text-align: left;">Total de la cotización</th>
                    <th style="text-align: left;">Impuestos (%)</th>
                    <th>Acciones</th>
                  
                </tr>
              </thead>
              <tbody>
                {% for cotizacion in cotizaciones %}
                <tr>
                    <td style="text-align: left;">{{cotizacion.cliente}}</td>
                    <td style="text-align: left;">
                      {% for insumo in cotizacion.insumos.all %}
                      {{insumo.nombre}}
                      {% endfor %}
                    </td>

                    <td style="text-align: left;">Bs. {{cotizacion.total}}</td>
                    <td style="text-align: left;">{{cotizacion.impuesto}}%</td>
                    <td>
                      <div style="display: flex; justify-content: center; gap: 5px; align-items: center;">
                        <button type="button" class="btn btn-danger" style="padding:10px;" data-toggle="modal" data-target="#confirmDeleteModal{{ cotizacion.id_cotizacion }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19 4h-3.5l-1-1h-5l-1 1H5v2h14M6 19a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7H6v12Z"/></svg>
                        </button>
                    </div>
                    <div class="modal fade" id="confirmDeleteModal{{ cotizacion.id_cotizacion }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalLabel">Confirmar Eliminación</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" style="width: 100%;overflow-wrap: anywhere;white-space: normal;">
                                    ¿Estás seguro de que deseas eliminar esta cotizacion? <br> 
                                    <strong>{{cotizacion.cliente}} / {{cotizacion.total}}</strong>
                                    
                                </div>
                                <div class="modal-footer">
                                    <!-- Formulario para enviar la solicitud de eliminación -->
                                    <form action="{% url 'web:eliminar_cotizacion' id_cotizacion=cotizacion.id_cotizacion %}" method="post">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <input type="submit" class="btn btn-danger" value="Eliminar">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    </td>
                </tr>
                
                    
                {% endfor %}
               
              </tbody>
            </table>
            {% if not cotizaciones %}
            <div style="width: 100%;text-align: center;justify-content: center;padding: 10px;">
                <div style="text-align: center;width: 100%;justify-content: center;">No hay cotizaciones registradas</div>
            </div>
            {% endif %}
            <div class="pagination" style="width: 100%;justify-content: center;align-items: center;">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; primera</a>
                        <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
                    {% endif %}
            
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <strong>{{ num }}</strong>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <a href="?page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
            
                    <span class="current">
                        Página {{ page_obj.number }} de {{ items.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">siguiente</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
                    {% endif %}
                </span>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    
    
    
  </div>
{% endblock %}

templates/pages/cotizaciones/crear.html
{% extends 'index.html' %}

{% block contenido %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body text-center">
                <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                    <h4 class="card-title">CREAR COTIZACIÓN</h4>
                    <a href="{% url 'web:cotizaciones' %}" class="btn " style="border-radius: 10px;background-color: rgb(224, 224, 224);font-weight: bold;padding: 10px;color: rgb(92, 92, 92);align-items: center;">Cancelar</a>
                </div>

                <div class="table-responsive" style="width: 100%;display: flex;justify-content: center;padding: 20px;">
                    <form method="post" style="max-width: 250px;display: flex;flex-direction: column;align-items: center;text-align: left;gap: 5px;">
                        {% csrf_token %}
                        <div style="width: 100%;">
                            {{ form.as_p }}
                        </div>
                        
                        {% if form.non_field_errors %}
                        <div class="alert alert-danger">
                            {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                    
                        <div id="loadingMessage" style="display: none;">
                            <p>Guardando cotización, por favor espere...</p>
                        </div>
                    
                        <button class="btn btn-primary" style="margin-top: 10px;" type="submit" id="submitBtn">Guardar Cotización</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        document.querySelector('form').addEventListener('submit', function() {
            document.getElementById('loadingMessage').style.display = 'block';
            document.getElementById('submitBtn').disabled = true;
        });
    </script>
</div>
{% endblock %}