apps/web/urls.py
# En el archivo urls.py en tu proyecto principal
from django.urls import include, path,re_path
from django.contrib.auth.decorators import login_required
from .views import login_view,ResultadoAnalisisDetailView,Usuarios,eliminar_venta,eliminar_fase,editar_fase,FasesListView,crear_cotizacion,editar_cliente,crear_cliente,editar_proveedor,crear_proveedor,crear_usuario,editar_insumo,crear_compra,crear_insumo,crear_servicio,crear_inventario,crear_sucursal,EditarSucursal,RegistrarVenta,EditarUsuario,eliminar_cotizacion,eliminar_cliente,eliminar_recibo,eliminar_proveedor,eliminar_insumo,eliminar_compra,eliminar_sucursal,Inicio,eliminar_servicio,eliminar_inventario,eliminar_usuario,ResultadoAnalisis,Clientes,Cotizaciones,Ventas,Facturas,Recibos,Sucursales,Servicios,Inventarios,Compras,Insumos,Proveedores
from django.contrib.auth.views import LogoutView

app_name = 'web' 

urlpatterns = [

    path('', login_view, name='login'),
    path('logout/', login_required(LogoutView.as_view(next_page="web:login")), name='logout'),
    path('dashboard', login_required(Inicio.as_view()),name='inicio'), 
    path('analisis', login_required(ResultadoAnalisis.as_view()),name='analisis'), 
    path('facturas', login_required(Facturas.as_view()),name='facturas'), 
    path('recibos', login_required(Recibos.as_view()),name='recibos'), 
    re_path(r'^recibos/eliminar/(?P<id_recibo>[-\w]+)/$', login_required(eliminar_recibo), name='eliminar_recibo'),
    path('sucursales', login_required(Sucursales.as_view()),name='sucursales'),
    re_path(r'^sucursales/eliminar/(?P<id_sucursal>[-\w]+)/$', login_required(eliminar_sucursal), name='eliminar_sucursal'),
    path('sucursales/editar/<str:pk>/', EditarSucursal.as_view(), name='editar_sucursal'),
    path('sucursales/crear/', crear_sucursal, name='crear_sucursal'),
    path('servicios', Servicios.as_view(),name='servicios'),
    re_path(r'^servicios/eliminar/(?P<id_servicio>[-\w]+)/$', login_required(eliminar_servicio), name='eliminar_servicio'),
    path('servicios/crear/', crear_servicio, name='crear_servicio'),
    path('inventarios', Inventarios.as_view(),name='inventarios'),
    re_path(r'^inventarios/eliminar/(?P<id_inventario>[-\w]+)/$', login_required(eliminar_inventario), name='eliminar_inventario'),
    path('inventarios/crear/', crear_inventario, name='crear_inventario'),
    path('compras', Compras.as_view(),name='compras'),
    re_path(r'^compras/eliminar/(?P<id_compra>[-\w]+)/$', login_required(eliminar_compra), name='eliminar_compra'),
    path('compras/crear/', crear_compra, name='crear_compra'),
    path('insumos', Insumos.as_view(),name='insumos'),
    re_path(r'^insumos/eliminar/(?P<id_insumo>[-\w]+)/$', login_required(eliminar_insumo), name='eliminar_insumo'),
    path('insumos/crear/', crear_insumo, name='crear_insumo'),
    path('insumos/editar/<str:id_insumo>/', editar_insumo, name='editar_insumo'),
    path('proveedores', Proveedores.as_view(),name='proveedores'),
    path('proveedores/editar/<str:id_proveedor>/', editar_proveedor, name='editar_proveedor'),
    re_path(r'^proveedores/eliminar/(?P<id_proveedor>[-\w]+)/$', login_required(eliminar_proveedor), name='eliminar_proveedor'),
    path('proveedores/crear/', crear_proveedor, name='crear_proveedor'),
    path('clientes', Clientes.as_view(),name='clientes'),
    re_path(r'^clientes/eliminar/(?P<id_cliente>[-\w]+)/$', login_required(eliminar_cliente), name='eliminar_cliente'),
    path('clientes/crear/', crear_cliente, name='crear_cliente'),
    path('clientes/editar/<str:id_cliente>/', editar_cliente, name='editar_cliente'),
    path('cotizaciones', Cotizaciones.as_view(),name='cotizaciones'),
    re_path(r'^cotizaciones/eliminar/(?P<id_cotizacion>[-\w]+)/$', login_required(eliminar_cotizacion), name='eliminar_cotizacion'),
    path('cotizaciones/crear/', crear_cotizacion, name='crear_cotizacion'),
    path('ventas', Ventas.as_view(),name='ventas'),
    re_path(r'^ventas/eliminar/(?P<id_venta>[-\w]+)/$', login_required(eliminar_venta), name='eliminar_venta'),
    path('ventas/registrar/', login_required(RegistrarVenta.as_view()), name='registrar_venta'),
    path('usuarios', login_required(Usuarios.as_view()),name='usuarios'),
    re_path(r'^usuarios/eliminar/(?P<id>\d+)/$', login_required(eliminar_usuario), name='eliminar_usuario'),
    path('usuarios/editar/<int:pk>/', EditarUsuario.as_view(), name='editar_usuario'),
    path('usuarios/crear', crear_usuario, name='crear_usuario'),

    path('fases', FasesListView.as_view(), name='fases'),  # Puedes ajustar la URL según tu preferencia
    path('fases/editar/<str:id_fase>/', editar_fase, name='editar_fase'),
    re_path(r'^fases/eliminar/(?P<id_fase>[-\w]+)/$', login_required(eliminar_fase), name='eliminar_fase'),

    path('resultado_analisis/<str:id_resultado>/', ResultadoAnalisisDetailView.as_view(), name='detalle_resultado'),

]

config/urls.py
# En el archivo urls.py en tu proyecto principal
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



admin.site.site_header  =  "IMPRENTA"  
admin.site.site_title  =  "Administracion"
admin.site.index_title  =  "Servicios de Imprenta"

urlpatterns = [
    path('',include('apps.web.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/compras/models.py
from django.db import models
import uuid
import shortuuid
from django.db.models.signals import post_save
from django.dispatch import receiver



def conver_encode():
    u = uuid.uuid4()
    s = shortuuid.encode(u)
    return s


class Compra(models.Model):
    id_compra = models.CharField(primary_key=True, max_length=100, unique=True, default=conver_encode, editable=False)
    proveedor = models.ForeignKey('Proveedor', blank=False, null=False, related_name="compras", on_delete=models.CASCADE, verbose_name="Proveedor")
    inventario = models.ForeignKey('empresa.Inventario', blank=False, null=False, related_name="compras", on_delete=models.CASCADE, verbose_name="Inventario")
    total_compra = models.FloatField(default=0, blank=False, null=False, verbose_name="Total de la compra", editable=False)
    factura = models.BooleanField(default=False, verbose_name="Facturado")
    impuesto_iva = models.IntegerField(default=13, blank=False, null=False, verbose_name="IMPUESTO IVA %", editable=False)
    impuesto_it = models.IntegerField(default=3, blank=False, null=False, verbose_name="IMPUESTO IT %", editable=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.id_compra

    class Meta:
        verbose_name = "Compra"
        verbose_name_plural = "Compras"
        db_table = "compra"


class DetalleCompra(models.Model):
    id_detalle_compra = models.CharField(primary_key=True,max_length=100,unique=True,default=conver_encode,editable=False)
    compra = models.ForeignKey('Compra', on_delete=models.CASCADE, related_name='detalles',verbose_name="Compra")
    insumo = models.ForeignKey('Insumo', on_delete=models.CASCADE,verbose_name="Insumo")
    cantidad = models.PositiveIntegerField(default=0,verbose_name="Cantidad",blank=False,null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.insumo.nombre} ({self.cantidad})"
    
    class Meta():
        verbose_name="Detalle de la Compra"
        verbose_name_plural="Detalles de las Compras"
        db_table="detalle_compra"


@receiver(post_save, sender=DetalleCompra)
def handle_detalle_compra_post_save(sender, instance, **kwargs):
    from apps.ventas.models import Factura, Recibo
    from apps.empresa.models import StockInsumo
    
    compra = instance.compra

    # Calcula el total de la compra
    suma_precios = sum(detalle.insumo.precio * detalle.cantidad for detalle in compra.detalles.all())
    compra.total_compra = suma_precios

    # Aplica impuestos si la compra está facturada
    if compra.factura:
        impuesto_total = compra.impuesto_iva + compra.impuesto_it
        compra.total_compra += (compra.total_compra * impuesto_total) / 100

        # Verifica si ya existe una factura para esta compra
        factura_existente = Factura.objects.filter(tipo='Compra', detalle__icontains=f'Detalle de la compra {compra.id_compra}').first()

        if factura_existente:
            # Actualiza el total de la factura existente
            factura_existente.total = compra.total_compra
            factura_existente.save()
        else:
            # Crea la factura
            factura = Factura(
                nit=compra.proveedor.nit,
                razon_social=compra.proveedor.razon_social,
                tipo='Compra',
                detalle=f'Detalle de la compra {compra.id_compra}. Insumos: {", ".join(detalle.insumo.nombre for detalle in compra.detalles.all())}',
                total=compra.total_compra
            )
            factura.save()
    else:
        # Verifica si ya existe un recibo para esta compra
        recibo_existente = Recibo.objects.filter(tipo='Compra', detalle__icontains=f'Detalle del recibo de la compra {compra.id_compra}').first()

        if recibo_existente:
            # Actualiza el total del recibo existente
            recibo_existente.total = compra.total_compra
            recibo_existente.save()
        else:
            # Crea el recibo
            recibo = Recibo(
                tipo='Compra',
                detalle=f'Detalle del recibo de la compra {compra.id_compra}. Insumos: {", ".join(detalle.insumo.nombre for detalle in compra.detalles.all())}',
                total=compra.total_compra
            )
            recibo.save()

    # Actualiza el stock de insumos en el inventario
    for detalle in compra.detalles.all():
        stock, created = StockInsumo.objects.get_or_create(
            inventario=compra.inventario,
            insumo=detalle.insumo
        )

        stock.cantidad += detalle.cantidad
        stock.save()

    compra.save()


CHOICES_CATEGORIA=[
    ('Materiales de Impresion','Materiales de Impresion'),
    ('Herramientas y Equipos','Herramientas y Equipos'),
    ('Partes y Accesorios','Partes y Accesorios'),
    ('Embalaje','Embalaje'),
]

class Insumo(models.Model):
    id_insumo = models.CharField(primary_key=True,max_length=100,unique=True,default=conver_encode,editable=False)
    proveedor=models.ForeignKey('Proveedor',blank=False,null=False,related_name="insumos",on_delete=models.CASCADE,verbose_name="Proveedor")
    nombre = models.CharField(max_length=155, blank=False, null=False,verbose_name="Nombre")
    detalle = models.TextField(max_length=500, blank=True, null=True,verbose_name="Detalle")
    categoria = models.CharField(max_length = 125,verbose_name="Categoria",choices=CHOICES_CATEGORIA,blank=False,null=False)
    precio=models.FloatField(default=0,verbose_name="Precio")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre
    
    class Meta():
        verbose_name="Insumo"
        verbose_name_plural="Insumos"
        db_table="insumo"


class Proveedor(models.Model):
    id_proveedor = models.CharField(primary_key=True,max_length=100,unique=True,default=conver_encode,editable=False)
    nombre = models.CharField(max_length=155, blank=False, null=False,verbose_name="Nombre")
    direccion = models.CharField(max_length=255, blank=False, null=False,verbose_name="Dirección")
    correo_electronico = models.EmailField(max_length=255, blank=False, null=False,verbose_name="Correo Electrónico")
    celular = models.CharField(max_length=255, blank=True, null=True,verbose_name="Número de celular")
    nit = models.CharField(max_length=55, blank=True, null=True,verbose_name="NIT")
    razon_social = models.CharField(max_length=255, blank=True, null=True,verbose_name="Razón social")
    latitud = models.CharField(max_length=55, blank=True, null=True,verbose_name="Latitud")
    longitud = models.CharField(max_length=55, blank=True, null=True,verbose_name="Longitud")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nombre
    
    class Meta():
        verbose_name="Proveedor"
        verbose_name_plural="Proveedores"
        db_table="proveedor"

apps/compras/forms.py
from django import forms
from .models import Compra, DetalleCompra,Insumo,Proveedor



class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['style'] = 'text-align: left;width: 100%;margin: 0px;'

class CompraForm(forms.ModelForm):
    class Meta:
        model = Compra
        fields = ['proveedor', 'inventario', 'factura']
        exclude = ['impuesto_iva','impuesto_it']


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['style'] = 'text-align: left;width: 100%;margin: 0px;'

class DetalleCompraForm(forms.ModelForm):
    class Meta:
        model = DetalleCompra
        fields = ['insumo', 'cantidad']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['style'] = 'text-align: left;width: 100%;margin: 0px;'

class InsumoForm(forms.ModelForm):
    class Meta:
        model = Insumo
        fields = ['proveedor', 'nombre', 'detalle', 'categoria', 'precio']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control '
            field.widget.attrs['style'] = 'text-align: left; width: 100% !important; margin: 0px; padding: 5px;'

apps/compras/views.py
from django.shortcuts import render

# Create your views here.

templates/pages/compras/compras.html
{% extends 'index.html' %}

{% block contenido %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
      <div class="card">
        <div class="card-body text-center">
            <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                <h4 class="card-title">COMPRAS</h4>
                <a href="{% url 'web:crear_compra' %}" class="btn btn-primary style="border-radius: 10px;font-weight: bold;padding: 10px;color: white;align-items: center;" ><svg xmlns="http://www.w3.org/2000/svg" style="margin-right: 5px;" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19 13h-6v6h-2v-6H5v-2h6V5h2v6h6v2z"/></svg>Registrar Compra</a>
              </div>
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                    <th style="text-align: left;">Proveedor</th>
                    <th style="text-align: left;">Inventario</th>
                    <th style="text-align: left;">Total de la compra</th>
                    <th>Acciones</th>
                  
                </tr>
              </thead>
              <tbody>
                {% for compra in compras %}
                <tr>
                    <td style="text-align: left;">{{compra.proveedor}}</td>
                    <td style="text-align: left;">{{compra.inventario}}</td>
                    <td style="text-align: left;">Bs. {{compra.total_compra}}</td>
                 
                    <td>
                      <div style="display: flex; justify-content: center; gap: 5px; align-items: center;">
                        <button type="button" class="btn btn-danger" style="padding:10px;" data-toggle="modal" data-target="#confirmDeleteModal{{ compra.id_compra }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19 4h-3.5l-1-1h-5l-1 1H5v2h14M6 19a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7H6v12Z"/></svg>
                        </button>
                    </div>
                    <div class="modal fade" id="confirmDeleteModal{{ compra.id_compra }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalLabel">Confirmar Eliminación</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body" style="width: 100%;overflow-wrap: anywhere;white-space: normal;">
                                    ¿Estás seguro de que deseas eliminar esta compra? <br> 
                                    <strong>{{compra.proveedor}}/ ({{compra.inventario}})</strong>
                                    
                                </div>
                                <div class="modal-footer">
                                    <!-- Formulario para enviar la solicitud de eliminación -->
                                    <form action="{% url 'web:eliminar_compra' id_compra=compra.id_compra %}" method="post">
                                        {% csrf_token %}
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                        <input type="submit" class="btn btn-danger" value="Eliminar">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    </td>
                </tr>
                
                    
                {% endfor %}
               
              </tbody>
            </table>
            {% if not compras %}
            <div style="width: 100%;text-align: center;justify-content: center;padding: 10px;">
                <div style="text-align: center;width: 100%;justify-content: center;">No hay compras registradas</div>
            </div>
            {% endif %}
            <div class="pagination" style="width: 100%;justify-content: center;align-items: center;">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; primera</a>
                        <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
                    {% endif %}
            
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <strong>{{ num }}</strong>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <a href="?page={{ num }}">{{ num }}</a>
                        {% endif %}
                    {% endfor %}
            
                    <span class="current">
                        Página {{ page_obj.number }} de {{ items.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">siguiente</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
                    {% endif %}
                </span>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    
    
    
    
  </div>
{% endblock %}

templates/pages/compras/crear.html
{% extends 'index.html' %}

{% block contenido %}
{% load static %}
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body text-center">
                <div style="display: flex;width: 100%;justify-content: space-between;align-items: center;padding-left: 10px;padding-right: 10px;">
                    <h4 class="card-title">CREAR COMPRA</h4>
                    <a href="{% url 'web:compras' %}" class="btn " style="border-radius: 10px;background-color: rgb(224, 224, 224);font-weight: bold;padding: 10px;color: rgb(92, 92, 92);align-items: center;">Cancelar</a>
                </div>

                <div class="table-responsive" style="width: 100%;display: flex;justify-content: center;padding: 20px;">
                    <form method="post" style="max-width: 250px;display: flex;flex-direction: column;align-items: center;text-align: left;gap: 5px;">
                        {% csrf_token %}
                        <div style="width: 100%;">
                            {{ compra_form.as_p }}
                            {{ detalle_formset.as_table }}
                        </div>
                        

                        {% if compra_form.non_field_errors %}
                            <div class="alert alert-danger">
                                {% for error in compra_form.non_field_errors %}
                                    <p>{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endif %}

                        <div id="loadingMessage" style="display: none;">
                            <p>Guardando cambios, por favor espere...</p>
                            <!-- Puedes añadir aquí un ícono de carga si lo deseas -->
                        </div>

                        <button class="btn btn-primary" style="margin-top: 10px;" type="submit" id="submitBtn">Guardar Compra</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        // Selección del formulario en lugar del botón
        document.querySelector('form').addEventListener('submit', function() {
            // Muestra el mensaje de carga
            document.getElementById('loadingMessage').style.display = 'block';
            // Deshabilita el botón de envío para evitar envíos múltiples
            document.getElementById('submitBtn').disabled = true;
        });
    </script>
</div>
{% endblock %}